const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];let events=[],filtered=[],index=0,position=0,drag=false,startX=0,startPos=0,lastX=0,lastT=0,velocity=0;
const palettes=['linear-gradient(145deg,#5f1520,#df4b4b)','linear-gradient(145deg,#222942,#7986b6)','linear-gradient(145deg,#42300f,#d39a31)','linear-gradient(145deg,#1d463b,#48a585)','linear-gradient(145deg,#4d204e,#be5fbd)','linear-gradient(145deg,#202020,#777)','linear-gradient(145deg,#5d351d,#c77b45)'];
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const fmt=d=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',year:'numeric'}).format(new Date(d));
async function load(){try{let r=await fetch('/api/events');let j=await r.json();events=j.events||[];$('#updated').textContent='Обновлено '+new Date(j.updatedAt).toLocaleString('ru-RU');}catch(e){events=[];$('#updated').textContent='Источник временно недоступен';}hydrateCities();apply();}
function hydrateCities(){let cities=[...new Set(events.map(e=>e.city).filter(Boolean))].sort();$('#city').insertAdjacentHTML('beforeend',cities.map(c=>`<option>${esc(c)}</option>`).join(''));}
function apply(){let q=$('#search').value.trim().toLowerCase(),city=$('#city').value,lang=$('#language').value,days=$('#period').value,limit=days==='all'?Infinity:+days*864e5,now=Date.now();filtered=events.filter(e=>{let hay=[e.title,e.city,e.venue,e.description].join(' ').toLowerCase(),dt=new Date(e.date).getTime();return(!q||hay.includes(q))&&(city==='all'||e.city===city)&&(lang==='all'||e.language===lang)&&(dt>=now-864e5&&dt-now<=limit)});index=Math.min(index,Math.max(0,filtered.length-1));position=index;renderCarousel();renderGrid();}
function renderCarousel(){let c=$('#carousel');if(!filtered.length){c.innerHTML='<div class="loading-card">Нет спектаклей по этим фильтрам</div>';$('#total').textContent='00';return}c.innerHTML=filtered.slice(0,12).map((e,i)=>`<button class="poster" data-i="${i}" style="--poster:${palettes[i%palettes.length]}"><span class="poster-face"><span class="topline"><b>${esc(e.city)}</b><span>${fmt(e.date)}</span></span><h3>${esc(e.title)}<i>${e.language==='ru'?'на русском':'русские титры'}</i></h3><span class="bottomline"><span>${esc(e.venue||'Израиль')}</span><b>ОТКРЫТЬ ↗</b></span></span></button>`).join('');$('#total').textContent=String(Math.min(filtered.length,12)).padStart(2,'0');updateCarousel();$$('.poster',c).forEach(p=>p.onclick=()=>{if(Math.abs(velocity)<.15)openEvent(filtered[+p.dataset.i].id)});}
function updateCarousel(){let posters=$$('.poster'),n=posters.length;if(!n)return;position=Math.max(0,Math.min(n-1,position));posters.forEach((p,i)=>{let off=i-position;p.style.setProperty('--offset',off);p.style.setProperty('--distance',Math.round(Math.abs(off)));p.classList.toggle('active',Math.abs(off)<.5)});index=Math.round(position);$('#current').textContent=String(index+1).padStart(2,'0');}
function go(delta){position=Math.max(0,Math.min($$('.poster').length-1,Math.round(position)+delta));updateCarousel()}
function down(e){if(e.pointerType==='mouse'&&e.button!==0)return;drag=true;velocity=0;startX=lastX=e.clientX;startPos=position;lastT=performance.now();$('#carousel').classList.add('dragging');e.currentTarget.setPointerCapture?.(e.pointerId)}
function move(e){if(!drag)return;let width=Math.min(innerWidth*.44,430),now=performance.now(),dx=e.clientX-lastX;velocity=(dx/(now-lastT||16))*-1;lastX=e.clientX;lastT=now;position=startPos-(e.clientX-startX)/(width*.82);updateCarousel()}
function up(){if(!drag)return;drag=false;$('#carousel').classList.remove('dragging');position=Math.round(position+velocity*1.7);updateCarousel()}
function renderGrid(){let g=$('#grid');$('.empty').hidden=!!filtered.length;g.innerHTML=filtered.map((e,i)=>`<article class="event-card"><span class="num">${String(i+1).padStart(2,'0')} / ${e.language==='ru'?'РУССКИЙ':'ТИТРЫ'}</span><h3>${esc(e.title)}</h3><p>${esc(e.description||'Описание и актуальные детали доступны на странице организатора.')}</p><button data-id="${esc(e.id)}">ПОДРОБНЕЕ ↗</button><footer><span>${fmt(e.date)}</span><span>${esc(e.city)} · ${esc(e.venue||'')}</span></footer></article>`).join('');$$('.event-card button',g).forEach(b=>b.onclick=()=>openEvent(b.dataset.id));}
function openEvent(id){let e=events.find(x=>x.id===id);if(!e)return;$('#modalContent').innerHTML=`<div class="modal-body"><span class="label">${e.language==='ru'?'СПЕКТАКЛЬ НА РУССКОМ':'ПОСТАНОВКА С РУССКИМИ ТИТРАМИ'}</span><h2>${esc(e.title)}</h2><div class="meta"><span>${fmt(e.date)}</span><span>${esc(e.city)}</span><span>${esc(e.venue||'Площадка уточняется')}</span>${e.price?`<span>${esc(e.price)}</span>`:''}</div><p>${esc(e.description||'Полное описание, время и наличие мест смотри на странице продавца.')}</p><p><small>Источник: ${esc(e.source||'официальная афиша')}</small></p><a class="tickets" href="${esc(e.url)}" target="_blank" rel="noopener">ПЕРЕЙТИ К БИЛЕТАМ ↗</a></div>`;$('#modal').showModal()}
function init(){let c=$('#carousel');c.addEventListener('pointerdown',down);c.addEventListener('pointermove',move);c.addEventListener('pointerup',up);c.addEventListener('pointercancel',up);c.addEventListener('wheel',e=>{if(Math.abs(e.deltaX)>Math.abs(e.deltaY)||e.shiftKey){e.preventDefault();position+=e.deltaX/500;updateCarousel()}},{passive:false});$('.prev').onclick=()=>go(-1);$('.next').onclick=()=>go(1);addEventListener('keydown',e=>{if(e.key==='ArrowLeft')go(-1);if(e.key==='ArrowRight')go(1);if(e.key==='Escape')$('#modal').close()});['search','city','language','period'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',apply));$('.close').onclick=()=>$('#modal').close();let drawer=$('.drawer'),back=$('.backdrop');const toggle=on=>{drawer.classList.toggle('open',on);back.classList.toggle('open',on);document.body.classList.toggle('lock',on)};$('.menu').onclick=()=>toggle(true);$('.drawer-close').onclick=()=>toggle(false);back.onclick=()=>toggle(false);$('.drawer a').onclick=()=>toggle(false);addEventListener('mousemove',e=>{$('.cursor').style.left=e.clientX+'px';$('.cursor').style.top=e.clientY+'px'});$$('a,button,input,select').forEach(el=>{el.onmouseenter=()=>$('.cursor').style.cssText+=`;width:42px;height:42px;background:rgba(216,255,62,.15)`;el.onmouseleave=()=>$('.cursor').style.cssText+=`;width:18px;height:18px;background:transparent`});load()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
