import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Copy, Check, Download, FileJson, Clipboard, Wrench } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface OutputUtilitiesProps {
  optimizedPrompt: string;
  originalPrompt: string;
  improvements?: string[];
}

function buildJsonSpec(prompt: string, improvements?: string[]): string {
  // Parse the optimized prompt to extract structured data
  const lines = prompt.split('\n').filter(l => l.trim());
  
  // Try to extract task, instructions, constraints, output format
  let task = '';
  let instructions = '';
  const constraints: string[] = [];
  let outputFormat = '';
  const notes: string[] = [];

  let currentSection = '';
  for (const line of lines) {
    const lower = line.toLowerCase().trim();
    if (lower.startsWith('task:') || lower.startsWith('# task') || lower.startsWith('objective:')) {
      currentSection = 'task';
      task = line.replace(/^(task:|# task|objective:)\s*/i, '').trim();
    } else if (lower.startsWith('instruction') || lower.startsWith('# instruction') || lower.startsWith('steps:')) {
      currentSection = 'instructions';
    } else if (lower.startsWith('constraint') || lower.startsWith('# constraint') || lower.startsWith('rules:') || lower.startsWith('requirements:')) {
      currentSection = 'constraints';
    } else if (lower.startsWith('output') || lower.startsWith('# output') || lower.startsWith('format:')) {
      currentSection = 'output';
      outputFormat = line.replace(/^(output.*?:|# output.*?|format:)\s*/i, '').trim();
    } else if (lower.startsWith('note') || lower.startsWith('# note')) {
      currentSection = 'notes';
    } else {
      if (currentSection === 'task' && !task) task = line.trim();
      else if (currentSection === 'instructions') instructions += (instructions ? '\n' : '') + line.trim();
      else if (currentSection === 'constraints') constraints.push(line.replace(/^[-•*]\s*/, '').trim());
      else if (currentSection === 'output' && !outputFormat) outputFormat = line.trim();
      else if (currentSection === 'notes') notes.push(line.trim());
      else if (!task) task = line.trim();
      else instructions += (instructions ? '\n' : '') + line.trim();
    }
  }

  // Fallback: if no structured extraction, use the whole prompt
  if (!task && !instructions) {
    task = lines[0] || prompt.slice(0, 100);
    instructions = prompt;
  }

  const spec = {
    task: task || 'Prompt optimization result',
    instructions: instructions || prompt,
    constraints: constraints.length > 0 ? constraints : (improvements || ['No explicit constraints detected']),
    output_format: outputFormat || 'Not specified',
    notes: notes.length > 0 ? notes.join('; ') : 'Generated by TRI/TFM Pipeline',
  };

  return JSON.stringify(spec, null, 2);
}

export const OutputUtilities = ({ optimizedPrompt, originalPrompt, improvements }: OutputUtilitiesProps) => {
  const [copiedPrompt, setCopiedPrompt] = useState(false);
  const [copiedJson, setCopiedJson] = useState(false);
  const { toast } = useToast();

  const handleCopyPrompt = async () => {
    await navigator.clipboard.writeText(optimizedPrompt);
    setCopiedPrompt(true);
    setTimeout(() => setCopiedPrompt(false), 2000);
    toast({ title: 'Copied', description: 'Optimized prompt copied to clipboard' });
  };

  const handleCopyJson = async () => {
    const json = buildJsonSpec(optimizedPrompt, improvements);
    await navigator.clipboard.writeText(json);
    setCopiedJson(true);
    setTimeout(() => setCopiedJson(false), 2000);
    toast({ title: 'Copied', description: 'JSON Prompt Spec copied to clipboard' });
  };

  const handleDownload = () => {
    const json = buildJsonSpec(optimizedPrompt, improvements);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `prompt-spec-${Date.now()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({ title: 'Downloaded', description: 'Prompt spec file saved' });
  };

  return (
    <Card className="border border-border">
      <CardHeader className="pb-2">
        <CardTitle className="flex items-center gap-2 text-sm font-semibold">
          <Wrench className="w-4 h-4 text-primary" />
          Export Options
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="flex flex-wrap gap-2">
          <Button variant="outline" size="sm" onClick={handleCopyPrompt} className="gap-1.5">
            {copiedPrompt ? <Check className="w-3.5 h-3.5 text-green-500" /> : <Clipboard className="w-3.5 h-3.5" />}
            Copy Optimized Prompt
          </Button>
          <Button variant="outline" size="sm" onClick={handleCopyJson} className="gap-1.5">
            {copiedJson ? <Check className="w-3.5 h-3.5 text-green-500" /> : <FileJson className="w-3.5 h-3.5" />}
            Copy as JSON Spec
          </Button>
          <Button variant="outline" size="sm" onClick={handleDownload} className="gap-1.5">
            <Download className="w-3.5 h-3.5" />
            Download Prompt Spec
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};
