const seed=require('../events.json');
const sources=[
 {name:'Гешер',url:'https://www.gesher-theatre.co.il/ru/company/a/calendar/'},
 {name:'SHOWMAN',url:'https://showman.co.il/e/category/theatre/'},
 {name:'Afishka',url:'https://afishka.co.il/events/category/teater/'},
 {name:'BRAVO!',url:'https://ru.kupatbravo.co.il/'}
];
const months={января:0,февраля:1,марта:2,апреля:3,мая:4,июня:5,июля:6,августа:7,сентября:8,октября:9,ноября:10,декабря:11};
const clean=s=>s.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
const slug=s=>s.toLowerCase().replace(/[^a-zа-я0-9]+/gi,'-').replace(/^-|-$/g,'').slice(0,55);
function extract(html,base,source){const out=[];const re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){let text=clean(m[2]);if(text.length<5||text.length>180)continue;if(!/(спектак|театр|драма|комед|мюзикл|русск|титр|представлен|show|performance)/i.test(text))continue;let near=clean(html.slice(Math.max(0,m.index-600),Math.min(html.length,re.lastIndex+800)));if(!/(русск|титр|на русском|субтитр)/i.test(near)&&source!=='Гешер')continue;let dm=near.match(/(\d{1,2})\s+(января|февраля|марта|апреля|мая|июня|июля|августа|сентября|октября|ноября|декабря)(?:\s+(20\d{2}))?/i);if(!dm)continue;let year=+(dm[3]||new Date().getFullYear()),date=new Date(Date.UTC(year,months[dm[2].toLowerCase()],+dm[1],17));if(date.getTime()<Date.now()-864e5*2)continue;let href;try{href=new URL(m[1],base).href}catch{continue}let language=/(на русском|русскоязыч|язык.*рус)/i.test(near)?'ru':'sub';let title=text.replace(/купить|билеты|подробнее|заказать/gi,'').trim();if(title.length<4)continue;out.push({id:slug(title)+'-'+date.toISOString().slice(0,10),title,date:date.toISOString(),city:'Израиль',venue:source,language,description:'Найдено автоматическим мониторингом. Актуальные детали и город смотри на странице организатора.',url:href,source,verified:false});if(out.length>=20)break}return out}
async function scanSource(s){try{let r=await fetch(s.url,{headers:{'user-agent':'Mozilla/5.0 SCENA-IL/1.1'},signal:AbortSignal.timeout(2200)});if(!r.ok)return[];return extract(await r.text(),s.url,s.name)}catch{return[]}}
async function scan(){const lists=await Promise.all(sources.map(scanSource));return lists.flat()}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','s-maxage=43200, stale-while-revalidate=86400');res.setHeader('Vercel-CDN-Cache-Control','s-maxage=43200, stale-while-revalidate=86400');let live=await scan();let map=new Map;[...seed,...live].forEach(e=>{let key=(e.title+'|'+e.date.slice(0,10)+'|'+(e.city||'')).toLowerCase();if(!map.has(key)||e.verified)map.set(key,e)});let events=[...map.values()].filter(e=>new Date(e.date).getTime()>=Date.now()-864e5).sort((a,b)=>new Date(a.date)-new Date(b.date));res.status(200).json({events,updatedAt:new Date().toISOString(),sources:sources.map(s=>s.name),mode:live.length?'live+verified':'verified-fallback'})}
