const seed=[
['bernalda','Дом Бернарды Альбы','2026-07-20T19:30:00+03:00','Тель-Авив — Яффо','Театр Гешер','sub','Напряжённая постановка по Лорке о власти, страхе и свободе внутри закрытого дома.','https://www.gesher-theatre.co.il/ru/repertoire/a/view/?ContentID=2887','Гешер'],
['vysotsky','Параллели. Высоцкий','2026-07-21T18:30:00+03:00','Ашкелон','Эшколь а-Пайс','ru','Музыкально-драматическая работа о человеке, который пытается удержать себя в распадающейся реальности.','https://showman.co.il/e/spektakl-paralleli-vysotskiy-ashkelon/','SHOWMAN','146 ₪'],
['kadry-july','Кадры','2026-07-23T19:30:00+03:00','Хайфа','Театральная площадка','ru','Офисный абсурд, чёрный юмор и живая музыка. Современный спектакль театра ДОМ чёрной СОВЫ.','https://showman.co.il/e/kadry-dom-chernoy-sovy/','SHOWMAN','121–161 ₪'],
['alice','Алиса в стране чудес','2026-07-24T12:00:00+03:00','Тель-Авив','Зал Цукер','ru','Литературно-музыкальное представление: камерный оркестр, живое чтение и песочная анимация.','https://afishka.co.il/event/%D1%81%D0%BF%D0%B5%D0%BA%D1%82%D0%B0%D0%BA%D0%BB%D1%8C-%D1%81-%D0%B0%D0%BD%D0%B0%D1%82%D0%BE%D0%BB%D0%B8%D0%B5%D0%BC-%D0%B2%D0%B0%D0%B9%D1%81%D0%BC%D0%B0%D0%BD%D0%BE%D0%BC/','Afishka','от 136 ₪'],
['amok','Амок','2026-07-25T20:00:00+03:00','Тель-Авив — Яффо','Театр Маленький','sub','Камерная психологическая драма по Стефану Цвейгу о враче, унижении и движении к катастрофе.','https://ru.kupatbravo.co.il/announce/amok-malinky-theater','BRAVO!','76–116 ₪'],
['last-day','День последний','2026-07-30T19:30:00+03:00','Тель-Авив — Яффо','Театр Гешер','sub','Апокалиптические видения в стиле буфф — музыкальная сатира о страхах, обсессиях и конце света.','https://www.gesher-theatre.co.il/ru/repertoire/a/view/?ContentID=2897','Гешер'],
['not-light','Не тот свет','2026-08-05T19:30:00+03:00','Тель-Авив — Яффо','Театр Гешер','ru','Ксения Раппопорт в постановке Авдотьи Смирновой. Спектакль о незапланированной встрече двух своеобразных героев.','https://www.gesher-theatre.co.il/ru/repertoire/a/view/?ContentID=2833','Гешер'],
['yesterday','Вчерашний мир','2026-08-10T20:00:00+03:00','Иерусалим','Театр Микро','sub','Цвейг, декадентская Вена, семейная тайна и воздух исчезающей Европы.','https://ru.kupatbravo.co.il/announce/86413','BRAVO!','120 ₪'],
['crime','Преступление и наказание','2026-09-02T19:30:00+03:00','Тель-Авив — Яффо','Театр Гешер','sub','Достоевский, превращённый в тёмное, музыкальное и ироничное кабаре в постановке Александра Молочникова.','https://www.gesher-theatre.co.il/ru/repertoire/a/view/?ContentID=2824','Гешер'],
['kadry-sept','Кадры','2026-09-09T20:00:00+03:00','Израиль','Уточняется','ru','Дополнительный показ современной драмы о корпоративном языке и утрате собственного голоса.','https://showman.co.il/e/kadry-dom-chernoy-sovy/','SHOWMAN'],
['bloody','Bloody Mary','2026-09-16T19:30:00+03:00','Тель-Авив — Яффо','Театр Гешер','ru','Дмитрий Крымов и две королевы: цирк, буффонада и «Мария Стюарт» Шиллера.','https://www.gesher-theatre.co.il/ru/repertoire/a/view/?ContentID=2889','Гешер'],
['souls','Души','2026-10-21T19:00:00+03:00','Тель-Авив — Яффо','Театр Гешер','sub','Реалистическая фантазия в постановке Итая Тирана — яркая и визуально насыщенная история души, странствующей четыреста лет.','https://www.gesher-theatre.co.il/ru/repertoire/a/view/?ContentID=2840','Гешер']
].map(x=>({id:x[0],title:x[1],date:x[2],city:x[3],venue:x[4],language:x[5],description:x[6],url:x[7],source:x[8],price:x[9]||''}));
const sources=[
 {name:'Гешер',url:'https://www.gesher-theatre.co.il/ru/company/a/calendar/'},
 {name:'SHOWMAN',url:'https://showman.co.il/e/category/theatre/'},
 {name:'Afishka',url:'https://afishka.co.il/events/category/theatre/'},
 {name:'BRAVO!',url:'https://ru.kupatbravo.co.il/' }
];
const months={января:0,февраля:1,марта:2,апреля:3,мая:4,июня:5,июля:6,августа:7,сентября:8,октября:9,ноября:10,декабря:11};
const clean=s=>s.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
const slug=s=>s.toLowerCase().replace(/[^a-zа-я0-9]+/gi,'-').replace(/^-|-$/g,'').slice(0,55);
function extract(html,base,source){const out=[];const re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){let text=clean(m[2]);if(text.length<5||text.length>180)continue;if(!/(спектак|театр|драма|комед|мюзикл|русск|титр|представлен|show|performance)/i.test(text))continue;let near=clean(html.slice(Math.max(0,m.index-500),Math.min(html.length,re.lastIndex+650)));if(!/(русск|титр|на русском|субтитр)/i.test(near)&&source!=='Гешер')continue;let dm=near.match(/(\d{1,2})\s+(января|февраля|марта|апреля|мая|июня|июля|августа|сентября|октября|ноября|декабря)(?:\s+(20\d{2}))?/i);if(!dm)continue;let year=+(dm[3]||new Date().getFullYear()),date=new Date(Date.UTC(year,months[dm[2].toLowerCase()],+dm[1],17));if(date.getTime()<Date.now()-864e5*2)continue;let href;try{href=new URL(m[1],base).href}catch{continue}let language=/(на русском|русскоязыч|язык.*рус)/i.test(near)?'ru':'sub';let title=text.replace(/купить|билеты|подробнее|заказать/gi,'').trim();if(title.length<4)continue;out.push({id:slug(title)+'-'+date.toISOString().slice(0,10),title,date:date.toISOString(),city:'Израиль',venue:source,language,description:'Найдено автоматическим мониторингом. Актуальные детали и город смотри на странице организатора.',url:href,source});if(out.length>=25)break}return out}
async function scan(){let found=[];await Promise.all(sources.map(async s=>{try{let r=await fetch(s.url,{headers:{'user-agent':'Mozilla/5.0 SCENA-IL/1.0'},signal:AbortSignal.timeout(7000)});if(r.ok)found.push(...extract(await r.text(),s.url,s.name))}catch{}}));return found}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','s-maxage=21600, stale-while-revalidate=86400');let live=await scan(),map=new Map;[...seed,...live].forEach(e=>{let key=(e.title+'|'+e.date.slice(0,10)).toLowerCase();if(!map.has(key)||e.source!=='seed')map.set(key,e)});let events=[...map.values()].sort((a,b)=>new Date(a.date)-new Date(b.date));res.status(200).json({events,updatedAt:new Date().toISOString(),sources:sources.map(s=>s.name),mode:live.length?'live+curated':'curated-fallback'})}
